eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 30
  client:
    registryFetchIntervalSeconds: 30
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://149.248.21.17:8761/eureka

mybatis:
  mapper-locations: classpath:mybatis.mappers/*.xml

# 打印sql
logging:
  level:
    com.onepro.custom.mapper: DEBUG

#tx-lcn:
#  client:
#    manager-address: 127.0.0.1:8070
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 2000ms
