package com.alag.p2p.business.module.bid.server.mapper;

import com.alag.p2p.business.module.bid.api.model.BidInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface BidInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Tue Apr 02 02:28:02 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Tue Apr 02 02:28:02 CST 2019
     */
    int insert(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Tue Apr 02 02:28:02 CST 2019
     */
    int insertSelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Tue Apr 02 02:28:02 CST 2019
     */
    BidInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Tue Apr 02 02:28:02 CST 2019
     */
    int updateByPrimaryKeySelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Tue Apr 02 02:28:02 CST 2019
     */
    int updateByPrimaryKey(BidInfo record);

    Double selectAllBidMoney();
}